add_subdirectory(SwiftPrivate)
add_subdirectory(SwiftPrivateLibcExtras)
add_subdirectory(SwiftPrivateThreadExtras)

if(BUILD_TESTING)
  add_subdirectory(BlocksRuntimeStubs)
  add_subdirectory(RuntimeUnittest)
  add_subdirectory(StdlibUnittest)
  add_subdirectory(StdlibUnicodeUnittest)
  add_subdirectory(StdlibCollectionUnittest)
  if(NOT CMAKE_SYSTEM_NAME STREQUAL Windows)
    add_subdirectory(SwiftReflectionTest)
  endif()
  if(CMAKE_SYSTEM_NAME STREQUAL Darwin)
    add_subdirectory(OSLog)
    add_subdirectory(StdlibUnittestFoundationExtras)
  endif()
  if(SWIFT_ENABLE_EXPERIMENTAL_DIFFERENTIABLE_PROGRAMMING)
    add_subdirectory(DifferentiationUnittest)
  endif()
endif()
