
add_library(StdlibUnittestFoundationExtrasCXX OBJECT
  UnavailableFoundationMethodThunks.mm)

add_library(StdlibUnittestFoundationExtras
  StdlibUnittestFoundationExtras.swift)
target_link_libraries(StdlibUnittestFoundationExtras PRIVATE
  $<TARGET_OBJECTS:StdlibUnittestFoundationExtrasCXX>)
target_link_libraries(StdlibUnittestFoundationExtras PUBLIC
  StdlibUnittest)
