
add_library(CollectionUnittest
  StdlibCollectionUnittest.swift
  CheckCollectionInstance.swift
  CheckCollectionType.swift
  CheckMutableCollectionType.swift
  CheckRangeReplaceableCollectionType.swift
  CheckRangeReplaceableSliceType.swift
  CheckSequenceInstance.swift
  CheckSequenceType.swift
  COWLoggingArray.swift
  LoggingWrappers.swift
  MinimalCollections.swift
  RangeSelection.swift
  WriteBackMutableSlice.swift)
